lane :test do
  discord_notifier(
    webhook_url: ENV["DISCORD_KEY"],
    title: "Title",
    description: "Description",
    success: true,
    author:ENV['USER'],
    thumbnail_url:"https://cdn.discordapp.com/embed/avatars/0.png",
    image_url:"https://cdn.discordapp.com/embed/avatars/0.png"
  )
end
